CREATE DATABASE Locadora;

USE Locadora;

CREATE TABLE Modelo
(
	IdModelo	INT PRIMARY KEY IDENTITY,
	Modelo		VARCHAR(200) NOT NULL,
	MARCA		VARCHAR(200) NOT NULL,
)

CREATe TABLE Cliente
(
	IdCliente	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200) NOT NULL,
	CPF			VARCHAR(200) NOT NULL,
)

CREATE TABLE Veiculos
(
	IdVeiculos	INT PRIMARY KEY IDENTITY,
	IdModelo	INT FOREIGN KEY REFERENCES Modelo (IdModelo),
	Veiculos	VARCHAR(200) NOT NULL,
	Placa		VARCHAR(200) NOT NULL,
)

CREATE TABLE Empresa
(
	IdEmpresa	INT PRIMARY KEY IDENTITY,
	IdVeiculos	INT FOREIGN KEY REFERENCES Veiculos (IdVeiculos),
	IdCliente	INT FOREIGN KEY REFERENCES Cliente (IdCliente),
)