CREATE DATABASE  Clinica;

USE Clinica;

CREATE TABLE Dono
(
	IdDono		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200) NOT NULL,
)

CREATE TABLE Pet
(
	IdPet		INT PRIMARY KEY IDENTITY,
	IdDono		INT FOREIGN KEY REFERENCES Dono (IdDono),
	Nome		VARCHAR(200) NOT NULL,
	Raca		VARCHAR(200) NOT NULL,
)

CREATE TABLE Veterinario
(
	IdVet		INT PRIMARY KEY IDENTITY,
	IdPet		INT FOREIGN KEY REFERENCES Pet (IdPet),
	Nome		VARCHAR(200) NOT NULL,
)

CREATE TABLE Clinica
(
	IdClinica	INT PRIMARY KEY IDENTITY,
	IdVEt		INT FOREIGN KEY REFERENCES Veterinario (IdVet),
	Endereco	VARCHAR(200) NOT NULL,
)

CREATE TABLE Aniversario
(
	IdNiver		INT PRIMARY KEY IDENTITY,
	DataN		VARCHAR(200) NOT NULL,
)