CREATE DATABASE Optus;

USE Optus;

CREATE TABLE Artista
(
	IdArtista		INT PRIMARY KEY IDENTITY,
	Nome			VARCHAR(200) NOT NULL,
)

CREATE TABLE Estilos
(
	IdEstilos		INT PRIMARY KEY IDENTITY,
	Nome			VARCHAR(200) NOT NULL,
)

CREATE TABLE Permissao
(
	IdPermissao		INT PRIMARY KEY IDENTITY,
	Adimistrador	VARCHAR(200) NOT NULL,
	Comum			VARCHAR(200) NOT NULL,
)

CREATE TABLE Album
(
	IdAlbum			INT PRIMARY KEY IDENTITY,
	IdArtista		INT FOREIGN KEY REFERENCES Artista (IdArtista),
	IdEstilos		INT FOREIGN KEY REFERENCES Estilos (IdEstilos),
	Titulo			VARCHAR(200) NOT NULL,
	DataDeLanc		VARCHAR(200) NOT NULL,
	Localizacao		VARCHAR(200) NOT NULL,
	Minutos			VARCHAR(200) NOT NULL,
	AtivoNao		VARCHAR(200) NOT NULL,
)

CREATE TABLE Usuario
(
	IdUsuario		INT PRIMARY KEY IDENTITY,
	IdPermissao		INT FOREIGN KEY REFERENCES Permissao (IdPermissao),
	Email			VARCHAR(200) NOT NULL,
	Senha			VARCHAR(200) NOT NULL,
	Nome			VARCHAR(200) NOT NULL,
)